### ISSUE TITLE
Cannot install "request" package to R version  3.2.3?

### ISSUE THREAD

**Issue by ngmacha** [sckott/request#15]
Running install.packages("request") in Windows 10 version of Microsoft's MRO R version 3.2.3 (2015-12-10) gives following:

Warning message: package `request' is not available (for R version 3.2.3)

**Comment by sckott** [comment]
I don't have MRO R, so can't help on that front. I do have 3.2.3 normal R, and it installs just fine. 

The package is on the MRAN site https://mran.revolutionanalytics.com/package/request/ so I'm surprised it doesn't work for you. 

They do have a google forum you could try  https://groups.google.com/forum/#!forum/rropen

**Comment by ngmacha** [comment]
Thank you for a quick response! Yes, I tried on the CRAN's "normal" R 3.2.3 and everything works. So there must be something with Microsoft's engine, the same error I got for yours httping package too... Very strange!

Best regards

Mac Ha - Sent from iPhone

**Comment by sckott** [comment]
You should ask on that forum, I don't know anything about MRAN
